
version: '3'
services:
  web:
    build: ./
    image: havistin2
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      # Development server settings
      - FLASK_APP=main.py
      - FLASK_DEBUG=0 # FLASK_DEBUG=0 -> server will be reloaded when code changes

    command: uwsgi --http :80
